sudo: required
language: c
# perl:
# - "5.18"

install:
 - sudo apt-get -y --force-yes install perl
 - sudo apt-get -y --force-yes install csh

script:
  - which csh
  - ./travis-test.csh
#   - perl -f tmp.pl
#   - hardware/generator_z/top/run.csh

